<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'user_token' => Str::uuid(),
                'name' => 'Hector',
                'last_name' => 'Gonzalez',
                'email' => 'hector@gmail.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('12345678'),
                'admin_id' => null,
                'remember_token' => null,
                'external_id' => 'JDAIS8U7D9832FAW321',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'María',
                'last_name' => 'Pérez',
                'email' => 'maria.perez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('87654321'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'PQR4567XYZ',
                'external_auth' => 'Facebook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Juan',
                'last_name' => 'Martínez',
                'email' => 'juan.martinez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('mypassword'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'XYZ7890ABC',
                'external_auth' => 'LinkedIn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Lucía',
                'last_name' => 'Torres',
                'email' => 'lucia.torres@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('password123'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Carlos',
                'last_name' => 'Jiménez',
                'email' => 'carlos.jimenez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('securepass'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'LMN12345OPQ',
                'external_auth' => 'Twitter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Sofía',
                'last_name' => 'González',
                'email' => 'sofia.gonzalez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('mypassword1'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'ABC98765XYZ',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Diego',
                'last_name' => 'Rivera',
                'email' => 'diego.rivera@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('password456'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Valentina',
                'last_name' => 'Cruz',
                'email' => 'valentina.cruz@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('valentina123'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'DEF12345GHI',
                'external_auth' => 'Facebook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Luis',
                'last_name' => 'Fernández',
                'email' => 'luis.fernandez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('luisfernandez'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Angela',
                'last_name' => 'Ruiz',
                'email' => 'angela.ruiz@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('angela123'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'GHI67890JKL',
                'external_auth' => 'LinkedIn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Fernando',
                'last_name' => 'Torres',
                'email' => 'fernando.torres@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('ferndando456'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Claudia',
                'last_name' => 'Ríos',
                'email' => 'claudia.rios@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('claudia789'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'JKL12345MNO',
                'external_auth' => 'Twitter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Pablo',
                'last_name' => 'Salazar',
                'email' => 'pablo.salazar@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('pablo1234'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Isabel',
                'last_name' => 'Morales',
                'email' => 'isabel.morales@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('isabel2024'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => 'MNO45678PQR',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'Ricardo',
                'last_name' => 'López',
                'email' => 'ricardo.lopez@example.com',
                'phone' => null,
                'verified_at' => now(),
                'password' => Hash::make('ricardo2023'),
                'admin_id' => null,
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // Insert 2 admin users
                'user_token' => Str::uuid(),
                'name' => 'Marco',
                'last_name' => 'Perez',
                'email' => 'marco@canvolt.com.mx',
                'phone' => '33 3258 8070',
                'verified_at' => now(),
                'password' => Hash::make('Canvolt2024!'),
                'admin_id' => 1,
                'remember_token' => null,
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_token' => Str::uuid(),
                'name' => 'David',
                'last_name' => 'Loera',
                'email' => 'davidarturoloera@gmail.com',
                'phone' => '33 3947 2308',
                'verified_at' => now(),
                'password' => Hash::make('Canvolt2024!'),
                'admin_id' => 2,
                'remember_token' => null,
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
