<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Hector Gonzalez',
                'email' => 'hector@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'remember_token' => null,
                'external_id' => 'JDAIS8U7D9832FAW321',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Loera',
                'email' => 'david@canvolt.com.mx',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'María Pérez',
                'email' => 'maria.perez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('87654321'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'PQR4567XYZ',
                'external_auth' => 'Facebook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Juan Martínez',
                'email' => 'juan.martinez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('mypassword'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'XYZ7890ABC',
                'external_auth' => 'LinkedIn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucía Torres',
                'email' => 'lucia.torres@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos Jiménez',
                'email' => 'carlos.jimenez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('securepass'),
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'external_id' => 'LMN12345OPQ',
                'external_auth' => 'Twitter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sofía González',
                'email' => 'sofia.gonzalez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('mypassword1'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'ABC98765XYZ',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diego Rivera',
                'email' => 'diego.rivera@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password456'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Valentina Cruz',
                'email' => 'valentina.cruz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('valentina123'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'DEF12345GHI',
                'external_auth' => 'Facebook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luis Fernández',
                'email' => 'luis.fernandez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('luisfernandez'),
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angela Ruiz',
                'email' => 'angela.ruiz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('angela123'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'GHI67890JKL',
                'external_auth' => 'LinkedIn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernando Torres',
                'email' => 'fernando.torres@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('ferndando456'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Claudia Ríos',
                'email' => 'claudia.rios@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('claudia789'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'JKL12345MNO',
                'external_auth' => 'Twitter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pablo Salazar',
                'email' => 'pablo.salazar@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('pablo1234'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabel Morales',
                'email' => 'isabel.morales@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('isabel2024'),
                'role' => 'user',
                'remember_token' => Str::random(10),
                'external_id' => 'MNO45678PQR',
                'external_auth' => 'Google',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ricardo López',
                'email' => 'ricardo.lopez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('ricardo2023'),
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'external_id' => null,
                'external_auth' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
